enable-magisk-update = false
cli-source = "ReVanced/revanced-cli"
parallel-jobs = 1

[Infinity]
patcher-args = "--options=client-id=$ID --enable='Spoof client' "
arch = "arm64-v8a"

# 403 CF error
# apkmirror-dlurl = "https://apkmirror.com/apk/docile-alligator/infinity-for-reddit/"
uptodown-dlurl = "https://infinity-for-reddit.en.uptodown.com/android"


[YouTube]
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
arch = "arm64-v8a"
riplib = false
patcher-args = "-e 'Change package name' -OpackageName=app.revanced.android.youtube"

# 403 CF error
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"


[YouTube-Music]
app-name = "Music"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
arch = "arm64-v8a"
riplib = false
patcher-args = "-e 'Change package name' -OpackageName=app.revanced.android.apps.youtube.music"

# 403 CF error
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"


[TikTok]
version = "latest"
included-patches = "'Show seekbar' 'Disable login requirement' 'Fix Google login'"
exclusive-patches = true

# 403 CF error
# apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
